language: swift
osx_image: xcode9.4

env:
  - DESTINATION="platform=iOS Simulator,name=iPhone X,OS=11.4"
  - DESTINATION="platform=iOS Simulator,name=iPhone SE,OS=11.4"
  - DESTINATION="platform=iOS Simulator,name=iPhone 8 Plus,OS=11.4"
  - DESTINATION="platform=iOS Simulator,name=iPad Pro (10.5-inch),OS=11.4"
  - DESTINATION="platform=iOS Simulator,name=iPhone X,OS=10.3.2"
  - DESTINATION="platform=iOS Simulator,name=iPhone SE,OS=10.3.2"
  - DESTINATION="platform=iOS Simulator,name=iPhone 8 Plus,OS=10.3.2"
  - DESTINATION="platform=iOS Simulator,name=iPad Pro (10.5-inch),OS=10.3.2"

before_deploy:
  - npm i -g podspec-bump
  - git config --local user.name "Travis CI"
  - git config --local user.eamil "travis@travis-ci.org"

script:
  - set -o pipefail && xcodebuild test -scheme JazzySlideKitUITests -destination "$DESTINATION" | xcpretty

deploy:
  provider: script
  script: bash scripts/deploy.sh $TRAVIS_TAG JazzySlideKit.podspec
  on:
    branch: master
    tags: true