language: swift
osx_image: xcode9.4
xcode_project: JazzySlideKit.xcodeproj
xcode_scheme: JazzySlideKitUITests

before_deploy:
  - npm i -g podspec-bump
  - git config --local user.name "Travis CI"
  - git config --local user.eamil "travis@travis-ci.org"

deploy:
  provider: script
  script: bash scripts/deploy.sh $TRAVIS_TAG
  on:
    branch: master
    tags: true