language: swift

matrix:
  include:
    - osx_image: xcode9.4
      env: DESTINATION="platform=iOS Simulator,name=iPhone X,OS=11.4"
    - osx_image: xcode9.4
      env: DESTINATION="platform=iOS Simulator,name=iPhone SE,OS=11.4"
    - osx_image: xcode9.4
      env: DESTINATION="platform=iOS Simulator,name=iPhone 8 Plus,OS=11.4"
    - osx_image: xcode9.4
      env: DESTINATION="platform=iOS Simulator,name=iPad Pro (10.5-inch),OS=11.4"

script:
  - set -o pipefail && xcodebuild test -scheme JazzySlideKitUITests -destination "$DESTINATION" | xcpretty

before_deploy:
  - npm i -g podspec-bump
  - podspec-bump -w -i $TRAVIS_TAG

deploy:
  provider: script
  script: pod trunk push
  on:
    branch: master
    tags: true