language: swift
osx_image: xcode9.4
cache: cocoapods

env:
  - OS="11.4" DEVICE="iPhone X"
  - OS="11.4" DEVICE="iPhone 8"
  - OS="11.4" DEVICE="iPhone 8 Plus"
  - OS="11.4" DEVICE="iPad Pro (10.5-inch)"
  # The following devices are currently failing because it appears that the travis-ci maintainers have removed those simulators from the list of available simulators
  # - OS="10.3.1" DEVICE="iPhone 7" 
  # - OS="10.3.1" DEVICE="iPhone 7 Plus"
  # - OS="10.3.1" DEVICE="iPad Pro (10.5-inch)"

before_install:
  - set -e
  - set -o pipefail

script:
  - xcodebuild test -workspace SlideKit.xcworkspace -scheme SlideKitSnapshotTests -destination "platform=iOS Simulator,name=$DEVICE,OS=$OS" | xcpretty -c

jobs:
  include:
    - stage: deploy
      script:
        - npm i -g podspec-bump
        - podspec-bump -w -i $TRAVIS_TAG
        - pod trunk push 
      if: tag =~ /[0-9]+(\.[0-9]+)*/
      
