language: swift
osx_image: xcode9.4
xcode_workspace: JazzySlideKit.xcworkspace
xcode_schema: JazzySlideKitTests

before_install:
  - brew install node
  - npm i -g podspec-bump

before_deploy:
  - git config --local user.name "Travis CI"
  - git config --local user.eamil "travis@travis-ci.org"

deploy:
  provider: script
  script: bash scripts/deploy.sh $TRAVIS_TAG
  on:
    branch: master
    tags: true