language: swift
osx_image: xcode10.1
cache: cocoapods

env:
  - OS="12.1" DEVICE="iPhone XS Max"
  - OS="12.1" DEVICE="iPad Pro (11-inch)"
  - OS="11.4" DEVICE="iPhone X"
  - OS="11.4" DEVICE="iPad Pro (10.5-inch)"
  - OS="10.3" DEVICE="iPhone 6" 
  - OS="10.3" DEVICE="iPad (5th generation)"

before_install:
  - set -e
  - set -o pipefail
  - bundle install
  - bundle exec pod install

script:
  - xcodebuild test -workspace SlideKit.xcworkspace -scheme SlideKitSnapshotTests -destination "platform=iOS Simulator,name=$DEVICE,OS=$OS" | xcpretty -c

jobs:
  include:
    - stage: deploy
      script:
        - npx podspec-bump -w -i $TRAVIS_TAG
        - bundle exec pod trunk push 
      if: tag =~ /[0-9]+(\.[0-9]+)*/
      
